package fr.yoga.booking.domain.notification;

public enum NotificationType {
	BOOKED,
	UNBOOKED,
	CANCELED,
	PLACE_CHANGED,
	FREE_PLACE_AUTOMATICALLY_BOOKED,
	AVAILABLE_PLACE,
	REMINDER,
	PASSWORD_RESET,
	RENEW_CLASS_PACKAGE_CARD,
	RENEW_MONTH_CARD,
	RENEW_ANNUAL_CARD,
	UNPAID_CLASSES, 
	MESSAGE_TO_STUDENT;
}
