cors:
  allowed-origins: "*"

reminder:
  next-class: "4h"
password-reset:
  token-validity: "2m"
booking:
  unbook-until: "1h"
#  unbook-until: "5d"

mail:
  smtp:
#    auth: true
#    host: smtp.gmail.com
#    port: 465
#    socketFactory:
#      port: 465
#      class: javax.net.ssl.SSLSocketFactory
    auth: true
    starttls:
      enable: true
    host: smtp.gmail.com
    port: 587
deployment:
  web-app-base-url: http://localhost:8100

logging:
  level:
    fr.yoga.booking: DEBUG
    #org.springframework.security: DEBUG
#logging:
#  level:
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 846418150945-l87u18f42ncvr0teel6cd6kjioepjaud.apps.googleusercontent.com
#            client-secret: QgCd3xv6BYwfRIxawJQ_Q7dS
