cors:
  allowed-origins: "*"

low-balance:
  remaining-classes: 1
  month-card-remaining-duration: "5d"
  annual-card-remaining-duration: "5d"

reminder:
  next-class:
    trigger-before: "1d,90m"
  subscription:
    remaining-classes:
      trigger-before-next-class: "1d"
    month-card:
      trigger-before-next-class: "1d"
      trigger-before-expiration: "5d"
    annual-card:
      remains: "5d"
      trigger-before-next-class: "1d"
      trigger-before-expiration: "5d"
  register-interval: "PT1M"
scheduler:
  clean-interval: "PT1M"
password-reset:
  token-validity: "10m"
booking:
  unbook-until: "1h"
#  unbook-until: "5d"

mail:
  smtp:
#    auth: true
#    host: smtp.gmail.com
#    port: 465
#    socketFactory:
#      port: 465
#      class: javax.net.ssl.SSLSocketFactory
    auth: true
    starttls:
      enable: true
    host: smtp.gmail.com
    port: 587
deployment:
  web-app-base-url: http://localhost:8100

logging:
  level:
    fr.yoga.booking: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
spring:
  boot:
    admin:
      client:
        url: http://localhost:10080
        instance:
          metadata:
            user.name: monitoring
            user.password: monitoring

#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 846418150945-l87u18f42ncvr0teel6cd6kjioepjaud.apps.googleusercontent.com
#            client-secret: QgCd3xv6BYwfRIxawJQ_Q7dS
