cors:
  allowed-methods: GET,POST,OPTIONS,PATCH,PUT,DELETE
  allowed-headers: Access-Control-Allow-Origin,Content-Type,Access-Control-Allow-Headers,Authorization,X-Requested-With,Accept,Accept-Language

low-balance:
  remaining-classes: 1
  month-card-remaining-duration: "5d"
  annual-card-remaining-duration: "5d"

reminder:
  next-class:
    trigger-before: "90m"
  subscription:
    remaining-classes:
      trigger-before-next-class: "1d"
    month-card:
      trigger-before-next-class: "1d"
      trigger-before-expiration: "5d"
    annual-card:
      trigger-before-next-class: "1d"
      trigger-before-expiration: "5d"
  register-interval: "PT10M"
scheduler:
  clean-interval: "PT24H"
password-reset:
  token-validity: "1h"
  token-length: 8
booking:
  unbook-until: "1h"

ogham:
  email:
    template:
      classpath:
        path-prefix: /templates/email/
  sms:
    template:
      classpath:
        path-prefix: /templates/sms/
        path-suffix: .txt.ftl
  
logging:
  level:
    org.reflections.Reflections: ERROR
    
spring:
  jackson:
    deserialization:
      accept-empty-array-as-null-object: false
      accept-empty-string-as-null-object: false
      read-date-timestamps-as-nanoseconds: false
    serialization:
      write-durations-as-timestamps: true
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false
  thymeleaf:
    prefix: ""
    suffix: ""
  freemarker:
    prefix: ""
    suffix: ""
    
